#
# sprdwl_ng.ko
#
# Kbuild: for kernel building external module
#
# Note:
# - Please refer to modules/sample/Kbuild to find out what should be
#   done is this Kbuild file
#

ifeq ($(filter $(strip $(BSP_BOARD_WLAN_DEVICE)),sc2332 sc2355 marlin3_sipc marlin3_pcie),)
$(error no BSP_BOARD_WLAN_DEVICE, pls fix it !!!)
endif

WLAN_DEVICE := $(strip $(BSP_BOARD_WLAN_DEVICE))

#
# Source List
#

ifeq ($(strip $(WLAN_DEVICE)),marlin3_sipc marlin3_pcie)
KO_MODULE_PATH := $(src)/marlin3_pcie
else
KO_MODULE_PATH := $(src)/$(WLAN_DEVICE)
endif
KO_MODULE_NAME := sprdwl_ng
KO_MODULE_SRC  :=

KO_MODULE_SRC += \
	$(shell find $(KO_MODULE_PATH) -name "*.c")

#
# Build Options
#
ifeq ($(strip $(WLAN_DEVICE)),sc2332)
ccflags-y += -DDEBUG
else ifeq ($(strip $(WLAN_DEVICE)),sc2355)
ccflags-y += -DSC2355_FTR -DSC2355_TX_FILTER -DSC2355_QOS_MAP
ccflags-y += -DIBSS_SUPPORT -DIBSS_RSN_SUPPORT
ccflags-y += -DNAN_SUPPORT
ccflags-y += -DRTT_SUPPORT
ccflags-y += -DSC2355_RX_NO_LOOP
ccflags-y += -DACS_SUPPORT -DSC2355_HW_CSUM
ccflags-y += -DWMMAC_WFA_CERTIFICATION
ccflags-y += -DCOMPAT_SAMPILE_CODE
ccflags-y += -DRND_MAC_SUPPORT
ccflags-y += -DSOFTAP_HOOK
ccflags-y += -DATCMD_ASSERT
ccflags-y += -DTCPACK_DELAY_SUPPORT
  ifeq ($(strip $(BSP_BUILD_VARIANT)),userdebug)
  ccflags-y += -DCONFIG_SPRD_WCN_DEBUG
  endif
ccflags-y += -DSPLIT_STACK
else ifeq ($(strip $(WLAN_DEVICE)),marlin3_sipc)
ccflags-y += -DSC2355_FTR -DSC2355_TX_FILTER -DSC2355_QOS_MAP
ccflags-y += -DIBSS_SUPPORT -DIBSS_RSN_SUPPORT
ccflags-y += -DNAN_SUPPORT
ccflags-y += -DRTT_SUPPORT
#ccflags-y += -DSC2355_RX_NO_LOOP
ccflags-y += -DACS_SUPPORT -DSC2355_HW_CSUM
ccflags-y += -DWMMAC_WFA_CERTIFICATION
ccflags-y += -DCOMPAT_SAMPILE_CODE
ccflags-y += -DRND_MAC_SUPPORT
ccflags-y += -DSOFTAP_HOOK
ccflags-y += -DATCMD_ASSERT
ccflags-y += -DTCPACK_DELAY_SUPPORT
ccflags-y += -DSIPC_SUPPORT
  ifeq ($(strip $(BSP_BUILD_VARIANT)),userdebug)
  ccflags-y += -DCONFIG_SPRD_WCN_DEBUG
  endif
ccflags-y += -DSPLIT_STACK
endif
ifeq ($(strip $(WLAN_DEVICE)),marlin3_pcie)
ccflags-y += -DSC2355_FTR -DSC2355_TX_FILTER -DSC2355_QOS_MAP
ccflags-y += -DIBSS_SUPPORT -DIBSS_RSN_SUPPORT
ccflags-y += -DNAN_SUPPORT
ccflags-y += -DRTT_SUPPORT
#ccflags-y += -DSC2355_RX_NO_LOOP
ccflags-y += -DACS_SUPPORT -DSC2355_HW_CSUM
ccflags-y += -DWMMAC_WFA_CERTIFICATION
ccflags-y += -DCOMPAT_SAMPILE_CODE
ccflags-y += -DRND_MAC_SUPPORT
ccflags-y += -DSOFTAP_HOOK
ccflags-y += -DATCMD_ASSERT
ccflags-y += -DTCPACK_DELAY_SUPPORT
#ccflags-y += -DENABLE_PAM_WIFI
	ifeq ($(strip $(BSP_BUILD_VARIANT)),userdebug)
	ccflags-y += -DCONFIG_SPRD_WCN_DEBUG
	endif
ccflags-y += -DSPLIT_STACK
endif


#
# Final Objects
#
obj-m := $(KO_MODULE_NAME).o
# Comment it if the only object file has the same name with module

ifeq ($(strip $(WLAN_DEVICE)),marlin3_sipc)
KO_SRC_PATH := marlin3_pcie
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,main.o cfg80211.o txrx.o \
						cmdevt.o npi.o msg.o work.o vendor.o tcp_ack.o mm.o \
						reorder.o core_sc2355.o tx_msg_sc2355.o rx_msg_sc2355.o \
						if_sc2355.o qos.o edma_test.o)

$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,defrag.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,ibss.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,nan.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,tracer.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rf_marlin3.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rtt.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,api_version.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rnd_mac_addr.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,softap_hook.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,debug.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,txrx_buf_mm.o)
# support for sipc
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,sipc_txrx_mm.o sipc_debug.o)

else ifeq ($(strip $(WLAN_DEVICE)),marlin3_pcie)
KO_SRC_PATH := marlin3_pcie
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,main.o cfg80211.o txrx.o \
						cmdevt.o npi.o msg.o work.o vendor.o tcp_ack.o mm.o \
						reorder.o core_sc2355.o tx_msg_sc2355.o rx_msg_sc2355.o \
						if_sc2355.o qos.o edma_test.o)

$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,defrag.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,ibss.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,nan.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,tracer.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rf_marlin3.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rtt.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,api_version.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,rnd_mac_addr.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,softap_hook.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,debug.o)
$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,txrx_buf_mm.o)
# support for pam_wifi
#$(KO_MODULE_NAME)-y += $(addprefix $(KO_SRC_PATH)/,pam_wifi.o)
else
$(KO_MODULE_NAME)-y := $(patsubst $(src)/%.c,%.o,$(KO_MODULE_SRC))
endif
