
/*********************************** ai_apb REGS, phy_addr=0x27000000 ************************************/
#define REG_AI_APB_APB_EB                                             0x0000
#define REG_AI_APB_APB_RST                                            0x0004
#define REG_AI_APB_GEN_CLK_CFG                                        0x0008
#define REG_AI_APB_POWERVR_INT_STATUS                                 0x000C
#define REG_AI_APB_LPC_CFG_MTX_M0                                     0x0010
#define REG_AI_APB_LPC_CFG_MTX_S0                                     0x0014
#define REG_AI_APB_LPC_CFG_MTX_S1                                     0x0018
#define REG_AI_APB_LPC_CFG_MTX_S2                                     0x001C
#define REG_AI_APB_LPC_MAIN_MTX_M0                                    0x0020
#define REG_AI_APB_LPC_MAIN_MTX_M1                                    0x0024
#define REG_AI_APB_LPC_MAIN_MTX_S0                                    0x0028
#define REG_AI_APB_LPC_MAIN_MTX_S1                                    0x002C
#define REG_AI_APB_LPC_MAIN_MTX_MAIN                                  0x0030
#define REG_AI_APB_LPC_AB_TO_DDR                                      0x0034
#define REG_AI_APB_ASYNC_BRIDGE_TO_DDR                                0x0038
#define REG_AI_APB_AI_QOS_CTRL                                        0x003C
#define REG_AI_APB_LPC_CTRL                                           0x0040
#define REG_AI_APB_USER_GATE_FORCE_OFF                                0x0044
#define REG_AI_APB_USER_GATE_AUTO_GATE_EN                             0x0048
#define REG_AI_APB_AXI_BUSMON_CTRL                                    0x004C
#define REG_AI_APB_ASYNC_BRIDGE_DEBUG_BUS_R                           0x0050
#define REG_AI_APB_ASYNC_BRIDGE_DEBUG_BUS_W                           0x0054

/*********************************** ai_clk REGS, phy_addr=0x27004000 ************************************/
#define REG_AI_CLK_CGM_POWERVR_DIV_CFG                                0x0024
#define REG_AI_CLK_CGM_POWERVR_SEL_CFG                                0x0028
#define REG_AI_CLK_CGM_MAIN_MTX_DIV_CFG                               0x0030
#define REG_AI_CLK_CGM_MAIN_MTX_SEL_CFG                               0x0034
#define REG_AI_CLK_CGM_CFG_MTX_DIV_CFG                                0x003C
#define REG_AI_CLK_CGM_CFG_MTX_SEL_CFG                                0x0040
#define REG_AI_CLK_CGM_OCM_DIV_CFG                                    0x0048
#define REG_AI_CLK_CGM_OCM_SEL_CFG                                    0x004C
#define REG_AI_CLK_CGM_DVFS_SEL_CFG                                   0x0058

/*********************************** ai_dvfs_apb REGS, phy_addr=0x27008000 ************************************/
#define REG_AI_DVFS_APB_AI_DVFS_HOLD_CTRL                             0x0000
#define REG_AI_DVFS_APB_AI_DVFS_WAIT_WINDOW_CFG0                      0x0004
#define REG_AI_DVFS_APB_AI_MIN_VOLTAGE_CFG                            0x0024
#define REG_AI_DVFS_APB_AI_SW_DVFS_CTRL                               0x0038
#define REG_AI_DVFS_APB_AI_DVFS_FREQ_UPDATE_BYPASS0                   0x0048
#define REG_AI_DVFS_APB_CGM_AI_DVFS_CLK_GATE_CTRL                     0x0050
#define REG_AI_DVFS_APB_AI_DVFS_VOLTAE_DBG0                           0x0054
#define REG_AI_DVFS_APB_AI_POWERVR_DVFS_CGM_CFG_DBG                   0x0068
#define REG_AI_DVFS_APB_AI_MAIN_MTX_DVFS_CGM_CFG_DBG                  0x006C
#define REG_AI_DVFS_APB_AI_OCM_DVFS_CGM_CFG_DBG                       0x0070
#define REG_AI_DVFS_APB_AI_DVFS_STATE_DBG                             0x0130
#define REG_AI_DVFS_APB_POWERVR_INDEX0_MAP                            0x0154
#define REG_AI_DVFS_APB_POWERVR_INDEX1_MAP                            0x0158
#define REG_AI_DVFS_APB_POWERVR_INDEX2_MAP                            0x015C
#define REG_AI_DVFS_APB_POWERVR_INDEX3_MAP                            0x0160
#define REG_AI_DVFS_APB_POWERVR_INDEX4_MAP                            0x0164
#define REG_AI_DVFS_APB_POWERVR_INDEX5_MAP                            0x0168
#define REG_AI_DVFS_APB_POWERVR_INDEX6_MAP                            0x016C
#define REG_AI_DVFS_APB_POWERVR_INDEX7_MAP                            0x0170
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX0_MAP                           0x0174
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX1_MAP                           0x0178
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX2_MAP                           0x017C
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX3_MAP                           0x0180
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX4_MAP                           0x0184
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX5_MAP                           0x0188
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX6_MAP                           0x018C
#define REG_AI_DVFS_APB_MAIN_MTX_INDEX7_MAP                           0x0190
#define REG_AI_DVFS_APB_OCM_INDEX0_MAP                                0x0194
#define REG_AI_DVFS_APB_OCM_INDEX1_MAP                                0x0198
#define REG_AI_DVFS_APB_OCM_INDEX2_MAP                                0x019C
#define REG_AI_DVFS_APB_OCM_INDEX3_MAP                                0x01A0
#define REG_AI_DVFS_APB_OCM_INDEX4_MAP                                0x01A4
#define REG_AI_DVFS_APB_OCM_INDEX5_MAP                                0x01A8
#define REG_AI_DVFS_APB_OCM_INDEX6_MAP                                0x01AC
#define REG_AI_DVFS_APB_OCM_INDEX7_MAP                                0x01B0
#define REG_AI_DVFS_APB_POWERVR_DVFS_INDEX_CFG                        0x0794
#define REG_AI_DVFS_APB_POWERVR_DVFS_INDEX_IDLE_CFG                   0x0798
#define REG_AI_DVFS_APB_MAIN_MTX_DVFS_INDEX_CFG                       0x079C
#define REG_AI_DVFS_APB_MAIN_MTX_DVFS_INDEX_IDLE_CFG                  0x07A0
#define REG_AI_DVFS_APB_OCM_DVFS_INDEX_CFG                            0x07A4
#define REG_AI_DVFS_APB_OCM_DVFS_INDEX_IDLE_CFG                       0x07A8
#define REG_AI_DVFS_APB_AI_FREQ_UPD_STATE0                            0x0924
#define REG_AI_DVFS_APB_AI_GFREE_WAIT_DELAY_CFG0                      0x0944
#define REG_AI_DVFS_APB_AI_FREQ_UPD_TYPE_CFG0                         0x09AC
#define REG_AI_DVFS_APB_AI_DFS_IDLE_DISABLE_CFG0                      0x09B4
#define REG_AI_DVFS_APB_AI_DVFS_RESERVED_REG_CFG0                     0x0A58
#define REG_AI_DVFS_APB_AI_DVFS_RESERVED_REG_CFG1                     0x0A5C
#define REG_AI_DVFS_APB_AI_DVFS_RESERVED_REG_CFG2                     0x0A60
#define REG_AI_DVFS_APB_AI_DVFS_RESERVED_REG_CFG3                     0x0A64

/*********************************** ai_mtx REGS, phy_addr=0x2700C000 ************************************/
#define REG_AI_MTX_REGU_OT_CTRL_EN                                    0x0000
#define REG_AI_MTX_REGU_OT_CTRL_AW_CFG                                0x0004
#define REG_AI_MTX_REGU_OT_CTRL_AR_CFG                                0x0008
#define REG_AI_MTX_REGU_OT_CTRL_AX_CFG                                0x000C
#define REG_AI_MTX_REGU_LAT_EN                                        0x0010
#define REG_AI_MTX_REGU_LAT_W_CFG                                     0x0014
#define REG_AI_MTX_REGU_LAT_R_CFG                                     0x0018
#define REG_AI_MTX_REGU_LAT_STATUS                                    0x001C
#define REG_AI_MTX_REGU_BW_NRT_EN                                     0x0040
#define REG_AI_MTX_REGU_BW_NRT_W_CFG_0                                0x0044
#define REG_AI_MTX_REGU_BW_NRT_W_CFG_1                                0x0048
#define REG_AI_MTX_REGU_BW_NRT_R_CFG_0                                0x004C
#define REG_AI_MTX_REGU_BW_NRT_R_CFG_1                                0x0050
#define REG_AI_MTX_REGU_BW_NRT_STATUS                                 0x0054
#define REG_AI_MTX_REGU_AXQOS_GEN_EN                                  0x0060
#define REG_AI_MTX_REGU_AXQOS_GEN_CFG                                 0x0064
#define REG_AI_MTX_REGU_URG_CNT_CFG                                   0x0068
#define REG_AI_MTX_REGU_URG_CNT_VALUE                                 0x006C

/*********************************** ai_busmon REGS, phy_addr=0x27010000 ************************************/
#define REG_AI_BUSMON_CHN_CFG                                         0x0000
#define REG_AI_BUSMON_PEAK_WIN_LEN                                    0x0004
#define REG_AI_BUSMON_F_DN_RBW_SET                                    0x0008
#define REG_AI_BUSMON_F_DN_RLATENCY_SET                               0x000C
#define REG_AI_BUSMON_F_DN_WBW_SET                                    0x0010
#define REG_AI_BUSMON_F_DN_WLATENCY_SET                               0x0014
#define REG_AI_BUSMON_F_UP_RBW_SET                                    0x0018
#define REG_AI_BUSMON_F_UP_RLATENCY_SET                               0x001C
#define REG_AI_BUSMON_F_UP_WBW_SET                                    0x0020
#define REG_AI_BUSMON_F_UP_WLATENCY_SET                               0x0024
#define REG_AI_BUSMON_RTRANS_IN_WIN                                   0x0028
#define REG_AI_BUSMON_RBW_IN_WIN                                      0x002C
#define REG_AI_BUSMON_RLATENCY_IN_WIN                                 0x0030
#define REG_AI_BUSMON_WTRANS_IN_WIN                                   0x0034
#define REG_AI_BUSMON_WBW_IN_WIN                                      0x0038
#define REG_AI_BUSMON_WLATENCY_IN_WIN                                 0x003C
#define REG_AI_BUSMON_PEAKBW_IN_WIN                                   0x0040
